import type { Metadata } from "next";
import { ButtonGroup } from "../components/ButtonGroup";
import DashHeader from "../components/DashboardNavbar";

export const metadata: Metadata = {
  title: "dashboard - wordwise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <DashHeader />
        <ButtonGroup />
        {children}
      </body>
    </html>
  );
}
